---
title: "Knowledge Graphs"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: spacelab 
runtime: shiny
---

```{css selectize-input, echo = FALSE}
.selectize-control .selectize-input {
  max-height: 100px;
  overflow-y: auto;
}
```


```{r}
  devtools::load_all()
  #library(sgraph)

  dirpath = system.file('data', package = 'kgraph')
  m_embeds = get(load(file.path(dirpath, 'm_embeds.rds')))
  df_dict = get(load(file.path(dirpath, 'df_dict.rds')))
  df_pairs = get(load(file.path(dirpath, 'df_cuis_pairs.rds')))

  df_dict$desc = df_dict$label
  df_dict$color = df_dict$group_details
  #df_dict$group = df_dict$color

  df_pairs_cols = c('umls_id.x', 'umls_id.y')

  # debug
  concepts_embeds = rownames(m_embeds)
  pairs_intersect = intersect(concepts_embeds,
                              unique(unlist(df_pairs[df_pairs_cols])))

  # tail is more related to mental health
  # subset(df_dict, id %in% pairs_intersect)$label

  # select_cuis = tail(pairs_intersect, 500)
  select_cuis = pairs_intersect
  m_embeds = m_embeds[select_cuis, ]
  df_dict = subset(df_dict, id %in% select_cuis)

  target_strs = c('autistic spectrum', 'depressi', 'alcohol' ,'sleep',
		  'psychosis', 'dementia', 'insomnia')
  target_strs = 'suicid'
  target_idxs = grep(paste(target_strs, collapse = '|'), df_dict$label)
  target_cuis = df_dict$id[target_idxs]
  similarity = 'cosine'; threshold_projs = 5; label_grid_size = 200
  #

  react_fit = shiny::reactive({
      similarity = input$similarity
      threshold_projs = input$threshold_projs
      fit_kg = fit_embeds_to_pairs(m_embeds, df_pairs[df_pairs_cols],
				   similarity = similarity,
				   threshold_projs = 1 - threshold_projs / 100)
    })


  react_kgraph = shiny::reactive({
      fit_kg = react_fit()
      df_projs = fit_kg$df_projs
      target_cuis = input$selected_concepts
      kgraph = get_kgraph(target_cuis, df_projs, df_dict)
    })


  colors_mapping = get_color_map(c(unique(df_dict$color), 'Groups', 'Other'))

  react_sgraph = shiny::reactive({
      kgraph = react_kgraph()
      label_grid_size = input$label_grid_size
      sgraph = get_sgraph(kgraph, colors_mapping,
			  label_grid_cell_size = label_grid_size)
    })

  react_legend = shiny::reactive({
      kgraph = react_kgraph()
      gglegend = sgraph:::get_legend(colors_mapping,
					 unique(kgraph$df_nodes$clusters))
    })

  react_auc = shiny::reactive({
      fit_kg = react_fit()
      pROC::plot.roc(fit_kg$roc, print.auc = TRUE)
    })

  output$kg = sgraph::renderSgraph(react_sgraph())
  output$legend = shiny::renderPlot(grid::grid.draw(react_legend()))
  output$auc = shiny::renderPlot(react_auc(), res = 96)

```

# Options {.sidebar}

##

```{r}
  shiny::selectInput('similarity', 'Similarity', 
    c('inprod', 'cosine', 'cov_simi', 'norm_inprod'), selected = 'cosine')

  shiny::sliderInput('threshold_projs', 'False positive threshold (%)',
		     0, 100, 10)


  shiny::selectInput('selected_concepts', 'Selected Concepts',
                     sort(unique(df_dict$id)), multiple = TRUE,
                     selected = target_cuis, selectize = TRUE)

  # probably could depend on window size
  shiny::sliderInput('label_grid_size',
                     htmltools::HTML('Label grid size</br>(Smaller = more labels)'),
                     1, 2e3, 500, ticks = FALSE)
```

# Graph

##

###

```{r}
  # some target nodes have no groups ?
  # is drug abstinence linked to dementia ? lol
  fillPage(sgraph::sgraphOutput('kg', height = '100%'),
           absolutePanel(id = 'legend', class = 'panel panel-default',
                         fixed = TRUE, draggable = TRUE, top = 100,
    	                 left = 'auto', right = 20, bottom = 'auto',
    	                 width = 120, height = '400px',
                         plotOutput('legend', height = '400px')))
```

# AUC

##

###

```{r}
  shiny::plotOutput('auc', height = '100%')
```
